import { PrismaClient } from "../src/generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import { hash } from "bcryptjs";

const adapter = new PrismaPg({
  host: "localhost",
  port: 5432,
  user: "postgres",
  password: "postgres",
  database: "cotizador_e3",
});
const prisma = new PrismaClient({ adapter });

async function main() {
  console.log("Seeding database...");

  const adminHash = await hash("cee564F1.", 10);
  const asesorHash = await hash("asesor123", 10);

  await prisma.user.upsert({
    where: { email: "urieljareth@gmail.com" },
    update: { password: adminHash },
    create: {
      email: "urieljareth@gmail.com",
      password: adminHash,
      name: "Uriel Jareth Alvarado Ortiz",
      role: "admin",
    },
  });

  await prisma.user.upsert({
    where: { email: "asesor@urieljareth.com" },
    update: { password: asesorHash },
    create: {
      email: "asesor@urieljareth.com",
      password: asesorHash,
      name: "Lorena Soto",
      role: "asesor",
    },
  });

  // ── CATEGORIAS (must be created BEFORE servicios for FK) ──
  const categorias = [
    { nombre: "SEO", descripcion: "Optimizacion para motores de busqueda", color: "#10b981", orden: 1 },
    { nombre: "Marketing", descripcion: "Estrategia y marketing digital", color: "#6366f1", orden: 2 },
    { nombre: "Paid Media", descripcion: "Publicidad pagada en plataformas digitales", color: "#f59e0b", orden: 3 },
    { nombre: "Desarrollo Web", descripcion: "Diseno y desarrollo de sitios web y ecommerce", color: "#3b82f6", orden: 4 },
    { nombre: "Automatizaciones", descripcion: "Automatizacion de procesos y flujos de trabajo", color: "#8b5cf6", orden: 5 },
    { nombre: "CRM", descripcion: "Gestion de relaciones con clientes", color: "#ec4899", orden: 6 },
    { nombre: "Desarrollo Personalizado", descripcion: "Soluciones a medida y desarrollo custom", color: "#14b8a6", orden: 7 },
  ];

  const catMap: Record<string, string> = {};
  for (const cat of categorias) {
    const created = await prisma.categoria.upsert({
      where: { nombre: cat.nombre },
      update: { color: cat.color, orden: cat.orden },
      create: cat,
    });
    catMap[cat.nombre] = created.id;
  }

  const catAlias: Record<string, string> = {
    auditoria: "Marketing",
    estrategia: "Marketing",
    diseno: "Desarrollo Web",
    sitio_web: "Desarrollo Web",
    ecommerce: "Desarrollo Web",
    ads: "Paid Media",
    redes: "Marketing",
    seo: "SEO",
    contenido: "Marketing",
    crm: "CRM",
    acompanamiento: "Marketing",
    otros: "Desarrollo Personalizado",
  };

  const servicios = [
    {
      nombre: "Auditoria en Redes Sociales",
      descripcion: "Auditoria completa de presencia en redes sociales",
      fase: 0,
      tipoPago: "unico",
      precioBase: 2990,
      tiempoEntrega: "4 - 10 dias",
      categoria: "auditoria",
      orden: 1,
      entregablesDefault: [
        "Revision de presencia en redes sociales",
        "Analisis de contenido publicado",
        "Evaluacion de engagement",
        "Documento de Evaluacion Total de Auditoria",
        "Junta de Resultados",
      ],
    },
    {
      nombre: "Auditoria en Sitio Web",
      descripcion: "Auditoria tecnica y de rendimiento de sitio web",
      fase: 0,
      tipoPago: "unico",
      precioBase: 2990,
      tiempoEntrega: "4 - 10 dias",
      categoria: "auditoria",
      orden: 2,
      entregablesDefault: [
        "Seguridad de dominio (vulnerabilidades)",
        "Velocidad de sitio web (core web vital)",
        "Diseno responsivo",
        "Performance del sitio",
        "Revison de SEO On Page y Off Page",
        "Chequeo de listado del sitio en listas negras",
        "Chequeo de Malware y Codigo Malicioso",
        "Revision de Firewall en el Sitio",
        "Recomendaciones SEO",
        "Revision de Google Search Console",
        "Revision de pixeles de Google y FB Ads",
        "Documento de Evaluacion Total de Auditoria",
        "Junta de Resultados",
      ],
    },
    {
      nombre: "Auditoria en Ecommerce",
      descripcion: "Auditoria completa de tienda en linea",
      fase: 0,
      tipoPago: "unico",
      precioBase: 2990,
      tiempoEntrega: "4 - 10 dias",
      categoria: "auditoria",
      orden: 3,
      entregablesDefault: [
        "Revision de Seguridad de dominio",
        "Revision de Certificado SSL",
        "Revision de Metodos de Pago",
        "Revision de Metodos de Envio",
        "Revision de Velocidad de Sitio Web",
        "Revision de Categorizacion de Productos",
        "Revision de Filtrado de Productos",
        "Revision de Carritos Abandonados",
        "Revision de Correos Transaccionales",
        "Revision de Pasos de Checkout",
        "Documento de Evaluacion Total de Auditoria",
        "Junta de Resultados",
      ],
    },
    {
      nombre: "Auditoria de cuentas Google Ads y Meta Ads",
      descripcion: "Auditoria de cuentas publicitarias",
      fase: 0,
      tipoPago: "unico",
      precioBase: 2990,
      tiempoEntrega: "4 - 10 dias",
      categoria: "auditoria",
      orden: 4,
      entregablesDefault: [
        "Revision de Configuracion General de Google Ads",
        "Revision de Configuracion de Facebook/Instagram Ads",
        "Revision de la Segmentacion de Publicos Personalizados",
        "Revision de Configuracion de Campanas",
        "Revision de Configuracion de Grupo de Anuncios",
        "Revision de Conversiones y Eventos Personalizados",
        "Revision de Integracion e Implementacion de Pixeles",
        "Revision de Estrategia de Presupuesto",
        "Revision de Anuncios Graficos",
        "Revision de Extensiones en los Anuncios",
        "Documento de Evaluacion Total de Auditoria",
        "Junta de Resultados",
      ],
    },
    {
      nombre: "Estudio Digital de Mercado",
      descripcion: "Estudio completo de mercado digital",
      fase: 1,
      tipoPago: "unico",
      precioBase: 4900,
      tiempoEntrega: "4 - 10 dias",
      categoria: "estrategia",
      orden: 5,
      entregablesDefault: [
        "Estudio de Competencia Organica",
        "Estudio de Competencia Pagada",
        "Estudio de Demanda",
        "Estudio de Tendencia",
        "Estudio de Segmentacion de Mercado",
        "Junta de Analisis de Resultados y Conclusiones",
      ],
    },
    {
      nombre: "Diseno de Identidad Corporativa",
      descripcion: "Creacion de identidad corporativa completa",
      fase: 1,
      tipoPago: "unico",
      precioBase: 11900,
      tiempoEntrega: "7 - 15 dias",
      categoria: "diseno",
      orden: 6,
      entregablesDefault: [
        "Creacion de Logotipo y Favicon",
        "Manual de Identidad Corporativa (colores, tipografias, usos)",
        "Plantillas para Redes Sociales (posts, historias, carruseles)",
        "Plantilla para portada de Redes Sociales",
        "Entrega de archivos editables",
        "Entrega de Mockups",
        "Aplicativos Digitales (firma electronica, diapositivas, wallpaper)",
        "Aplicativos Fisicos (tarjetas, hojas membretadas)",
        "Presentacion de Propuestas",
        "Tres juntas de revision",
      ],
    },
    {
      nombre: "Diseno de Sitio Web (WordPress)",
      descripcion: "Diseno y desarrollo de sitio web en WordPress",
      fase: 1,
      tipoPago: "unico",
      precioBase: 35000,
      tiempoEntrega: "4 - 8 semanas",
      categoria: "sitio_web",
      variante: "wordpress",
      orden: 7,
      entregablesDefault: [
        "Desarrollo y Estructuracion Jerarquica de Sitio Web",
        "Creacion de Paginas Basicas (TyC, PyP, Gracias, 404)",
        "Optimizacion Avanzada SEO en cada Pagina",
        "Sitio adaptado a ordenadores, tabletas y celulares (responsive)",
        "Configuracion Avanzada de Velocidad de Carga",
        "Diseno y Optimizacion de elementos graficos",
        "Integracion y Configuracion de Contacto por WhatsApp y Llamada",
        "Configuracion de Plugins de Seguridad",
        "Capacitacion Basica de Sitio",
        "Poliza de mantenimiento",
        "Respaldo de seguridad semanal",
        "Creacion y Optimizacion de Blog optimizado para SEO",
        "Integracion de Formulario",
        "Documento Estadisticas de Sitio Web (mensual)",
        "Indexacion en Motores de Busqueda",
        "Configuracion de Google Analytics 4, Tag Manager, Google Ads, Pixel y Capi de Facebook",
        "Configuracion de Google Search Console",
        "Revision de TyC, Politicas y Privacidad",
        "Creacion de Textos Comerciales",
        "Soporte de Primer y Segundo Nivel",
        "Dominio, Certificado SSL, Hosting Incluido (5GB) - 1 Ano",
        "Incluye tres revisiones del Proyecto",
      ],
    },
    {
      nombre: "Diseno de Ecommerce (WooCommerce)",
      descripcion: "Tienda en linea con WooCommerce",
      fase: 1,
      tipoPago: "unico",
      precioBase: 19900,
      tiempoEntrega: "4 - 8 semanas",
      categoria: "ecommerce",
      variante: "woocommerce",
      orden: 8,
      entregablesDefault: [
        "Desarrollo y Estructuracion de Ecommerce",
        "Creacion de Paginas Basicas (TyC, PyP, Gracias, 404)",
        "Optimizacion Avanzada SEO en cada Pagina de Productos y Categorias",
        "Diseno Responsivo (UI / UX)",
        "Configuracion Avanzada de Velocidad de Carga",
        "Diseno y Optimizacion de elementos graficos para cada Pagina",
        "Integracion y Configuracion de Contacto por WhatsApp y Llamada",
        "Integracion de Formulario",
        "Integracion de Plugins de Seguridad",
        "Capacitacion Basica de Sitio",
        "Integracion de Metodos de Pago",
        "Integracion de Metodos de Envio",
        "Configuracion Jerarquica de Categoria por Nivel",
        "Configuracion de Enlazado de Categorias",
        "Configuracion de Carritos Abandonados",
        "Documento Estadisticas de Sitio Web (mensual)",
        "Indexacion en Motores de Busqueda",
        "Configuracion de Google Analytics 4, Tag Manager, Google Ads, Pixel y Capi de Facebook para Ecommerce",
        "Configuracion de Google Search Console",
        "Incluye tres revisiones del Proyecto",
        "Dominio, Certificado SSL, Hosting Incluido (5GB) - 1 Ano",
        "Creacion de Textos Comerciales",
        "Desarrollo y Estructuracion de Blog",
      ],
    },
    {
      nombre: "Diseno Tienda en Linea (Shopify)",
      descripcion: "Tienda en linea con Shopify",
      fase: 1,
      tipoPago: "unico",
      precioBase: 21900,
      tiempoEntrega: "4 - 8 semanas",
      categoria: "ecommerce",
      variante: "shopify",
      orden: 9,
      entregablesDefault: [
        "Desarrollo y Estructuracion de Ecommerce",
        "Configuracion de Paginas Basicas (TyC, AyP, Contacto, Nosotros, 404)",
        "Configuracion de Paginas de Ecommerce (Mi cuenta, Inicio de sesion, Politicas)",
        "Configuracion y Personalizacion de Template",
        "Optimizacion SEO en cada Pagina de Productos y Categorias",
        "Diseno Responsivo (UI / UX)",
        "Configuracion de Velocidad de Carga en Sitio Web",
        "Diseno y Optimizacion de elementos graficos para cada Pagina",
        "Integracion y Configuracion de App de Contacto por WhatsApp",
        "Integracion de Apps para Metodos de Pago",
        "Integracion de Apps para Metodos de Envio",
        "Configuracion y Estructura de Menu Principal",
        "Soporte de Primer y Segundo Nivel",
        "Creacion de Categorias de Tienda",
        "Configuracion de Correos Base para Ecommerce",
        "Configuracion de Carritos Abandonados",
        "Indexacion en Motores de Busqueda",
        "Configuracion de Google Search Console",
        "Implementacion de Google Analytics 4",
        "Capi y Pixel de Facebook",
        "Creacion de Textos Comerciales",
        "Capacitacion Basica de Tienda",
        "Incluye tres revisiones del Proyecto",
        "Dominio",
      ],
    },
    {
      nombre: "Creacion y Optimizacion de Redes Sociales",
      descripcion: "Creacion y brandeo de perfiles en redes sociales",
      fase: 1,
      tipoPago: "unico",
      precioBase: 2500,
      tiempoEntrega: "4 - 10 dias",
      categoria: "redes",
      orden: 10,
      entregablesDefault: [
        "Creacion de Redes Sociales (Facebook, Instagram)",
        "Brandeo de las Redes y Optimizacion",
      ],
    },
    {
      nombre: "Creacion y Optimizacion de la Ficha de Google My Business",
      descripcion: "Configuracion y optimizacion de perfil de Google",
      fase: 1,
      tipoPago: "unico",
      precioBase: 2000,
      tiempoEntrega: "4 - 10 dias",
      categoria: "seo",
      orden: 11,
      entregablesDefault: [
        "Creacion y Configuracion de Perfil de Negocio de Google",
        "Optimizacion de Perfil de Negocio de Google",
        "Generacion de Mapas Fractales",
        "Plantillas para Publicaciones en Perfil de Negocio",
        "Reporte de resultados",
      ],
    },
    {
      nombre: "Configuracion y Puesta en Marcha del CRM Bucefalo",
      descripcion: "Configuracion inicial de cuenta CRM Bucefalo",
      fase: 1,
      tipoPago: "unico",
      precioBase: 3900,
      tiempoEntrega: "4 - 10 dias",
      categoria: "crm",
      orden: 12,
      entregablesDefault: [
        "Configuracion de cuenta CRM Bucefalo",
        "Curso de Capacitacion",
        "Configuracion de Automatizaciones",
        "Configuracion de Pipeline de Oportunidades",
        "Configuracion de Campos Personalizados",
        "Integracion de Calendario",
        "Configuracion de Reportes",
      ],
    },
    {
      nombre: "Configuracion, Optimizacion y Puesta en Marcha de Google Ads y Meta Ads",
      descripcion: "Setup completo de ambas plataformas publicitarias",
      fase: 1,
      tipoPago: "unico",
      precioBase: 4000,
      tiempoEntrega: "4 - 10 dias",
      categoria: "ads",
      orden: 13,
      entregablesDefault: [
        "Configuracion y estructura de las Campanas de Google Ads",
        "Configuracion de Conversiones",
        "Configuracion de la Segmentacion de Publicos Personalizados",
        "Configuracion de listas de terminos de busqueda negativos",
        "Configuracion de listas de terminos busqueda",
        "Configuracion de Anuncios publicitarios",
        "Configuracion de Extensiones en los anuncios",
        "Configuracion de Cuenta Facebook Ads e Instagram Ads",
        "Configuracion de Pixeles de Conversion",
        "Configuracion de Anuncios Publicitarios para Meta",
        "Configuracion de Conversiones Personalizadas",
      ],
    },
    {
      nombre: "Tablero de Inspiracion",
      descripcion: "Estrategia creativa para campanas publicitarias",
      fase: 2,
      tipoPago: "unico",
      precioBase: 2900,
      tiempoEntrega: "6 - 10 dias",
      categoria: "estrategia",
      orden: 14,
      entregablesDefault: [
        "Estrategia Creativa",
        "Segmentacion de Mercado",
        "Complexogramo",
        "Analisis de Competencia",
        "Analisis de los mejores Anuncios Locales, Nacionales e Internacionales",
      ],
    },
    {
      nombre: "Configuracion y Optimizacion Google Ads",
      descripcion: "Configuracion y optimizacion mensual de Google Ads",
      fase: 2,
      tipoPago: "mensual",
      precioBase: 4900,
      tiempoEntrega: "4 - 10 dias",
      categoria: "ads",
      orden: 15,
      entregablesDefault: [
        "Revision de la Segmentacion de Publicos Personalizados",
        "Revision de Listas de Terminos de Busqueda Negativos",
        "Revision de Listas de Terminos Busqueda",
        "Revision de Anuncios Publicitarios",
        "Revision de Anuncios Graficos",
        "Una Sesion de Acompanamiento para Google",
      ],
    },
    {
      nombre: "Manejo y Optimizacion de Meta Ads",
      descripcion: "Manejo y optimizacion mensual de Meta Ads",
      fase: 2,
      tipoPago: "mensual",
      precioBase: 1500,
      tiempoEntrega: "4 - 10 dias",
      categoria: "ads",
      orden: 16,
      entregablesDefault: [
        "Revision de la Configuracion de Conversiones",
        "Revision de la Segmentacion de Publicos Personalizados",
        "Revision de Conversiones Personalizadas",
        "Revision de Anuncios Publicitarios",
        "Una Sesion de Acompanamiento para la Creacion de Portafolio Comercial / Facebook",
      ],
    },
    {
      nombre: "Manejo Basico de Redes Sociales",
      descripcion: "Manejo mensual basico de redes sociales",
      fase: 2,
      tipoPago: "mensual",
      precioBase: 3000,
      tiempoEntrega: "4 - 10 dias",
      categoria: "redes",
      orden: 17,
      entregablesDefault: [
        "Realizacion de Parrilla, Diseno y Programacion",
        "3 - 5 Post Mensuales",
      ],
    },
    {
      nombre: "Plan Mensual CRM Bucefalo",
      descripcion: "Suscripcion mensual al CRM Bucefalo",
      fase: 2,
      tipoPago: "mensual",
      precioBase: 3900,
      tiempoEntrega: "Mensual",
      categoria: "crm",
      orden: 18,
      entregablesDefault: [
        "Uso completo del CRM segun plan contratado",
        "Soporte tecnico",
        "Actualizaciones del sistema",
      ],
    },
    {
      nombre: "Desarrollo de Plan de Contenido",
      descripcion: "Plan estrategico de contenido",
      fase: 3,
      tipoPago: "unico",
      precioBase: 2900,
      tiempoEntrega: "6 - 10 dias",
      categoria: "contenido",
      orden: 19,
      entregablesDefault: [
        "Analisis situacional de la marca",
        "Objetivos de la marca",
        "Analisis de Audiencia y Competencia",
        "Estrategias de Contenido",
        "Propuesta de Contenido",
        "Plan de Acciones",
        "Canales de Distribucion",
        "Medicion y Metricas",
      ],
    },
    {
      nombre: "Generacion de Contenido",
      descripcion: "Generacion mensual de contenido para redes",
      fase: 3,
      tipoPago: "mensual",
      precioBase: 8000,
      tiempoEntrega: "Mensual",
      categoria: "contenido",
      orden: 20,
      entregablesDefault: [
        "Manejo de Parrilla Mensual (Facebook, Instagram, Pinterest, YouTube, Tik Tok)",
        "Publicaciones Estaticas para Redes Sociales",
        "Post para Blog",
        "Video YouTube largo, Generacion de Reels, Shorts",
        "Escucha Social (analisis de opiniones de clientes)",
        "Junta de Reporte mensual",
      ],
    },
    {
      nombre: "Posicionamiento SEO",
      descripcion: "Posicionamiento SEO mensual",
      fase: 3,
      tipoPago: "mensual",
      precioBase: 2900,
      tiempoEntrega: "4 - 10 dias",
      categoria: "seo",
      orden: 21,
      entregablesDefault: [
        "Posicionamiento de KW (3 palabras clave)",
        "Traqueo de las Palabras Clave",
        "Creacion de Enlaces Externos al Sitio",
        "Citaciones para el Sitio",
        "Reporte de resultados (mensual)",
      ],
    },
    {
      nombre: "Estrategia SEO Completa",
      descripcion: "Estrategia SEO completa con contenido y backlinks",
      fase: 3,
      tipoPago: "mensual",
      precioBase: 2900,
      tiempoEntrega: "Mensual",
      categoria: "seo",
      orden: 22,
      entregablesDefault: [
        "Busqueda y definicion de KW a atacar",
        "Definicion de tematica y KW por Mes (calendario semestral)",
        "Monitoreo de posiciones en SERPS de KW",
        "Busqueda de backlinks de la competencia",
        "Gestion con medios y webs para el correcto enlazado",
        "Indexacion a Backlinks y monitoreo",
        "Generacion de contenido SEO para Post del blog o Landing",
        "Generacion de Imagenes y video para ilustracion",
        "Generacion de Url (post o Landing) para posicionamiento",
        "Optimizacion SEO de todas las Url nuevas",
        "Enlazado Interno de todo el sitio web",
        "Optimizacion de usabilidad del sitio",
        "Optimizacion de Copy",
        "Optimizacion de EEAT",
        "Optimizacion de enlazado interno",
        "Optimizacion de prominencia Semantica",
        "Reporte mensual",
      ],
    },
    {
      nombre: "Plan de Acompanamiento Integral",
      descripcion: "Servicio integral de acompanamiento estrategico y operativo durante un periodo minimo obligatorio de 9 meses (3 meses operando Uriel Jareth Consulting, 3 operando en conjunto y 3 meses operando en acompanamiento)",
      fase: 0,
      tipoPago: "mensual",
      precioBase: 9000,
      tiempoEntrega: "Minimo 9 meses",
      categoria: "acompanamiento",
      orden: 23,
      entregablesDefault: [
        "Manejo de Google Ads (Performance Max, Demand Gen, IA Max for Search)",
        "Implementacion con first-party data y third-party data",
        "Reportes mensuales con analisis de resultados Google Ads",
        "Manejo de Meta Ads (Advantage+, campanas por objetivo, remarketing dinamico)",
        "Segmentacion y automatizacion con IA",
        "Reportes mensuales con analisis de resultados Meta Ads",
      ],
    },

    // ──────────────────────────────────────────────────────────────
    // SERVICIOS NIVELADOS (Catalogo Uriel Jareth Consulting - Cotizacion Final)
    // Precios convertidos de USD a MXN al tipo de cambio 17.30
    // Niveles: Emprendedor / PYME / Empresario / Corporativo
    // ──────────────────────────────────────────────────────────────

    // ── LOGO E IDENTIDAD (Fase 1, unico) ──
    {
      nombre: "Logo e Identidad",
      descripcion: "Diseno de identidad de marca y logotipo",
      fase: 1,
      tipoPago: "unico",
      precioBase: 6903, // 399 USD
      tiempoEntrega: "7 - 15 dias",
      categoria: "diseno",
      nivel: "Emprendedor",
      orden: 101,
      entregablesDefault: [
        "Investigacion de Tendencias, Mercado, Competencia y Demanda",
        "Creacion y Propuesta del Naming: 2",
        "Propuesta del Logotipo: 2",
        "Creacion Logotipo",
        "Diseno de Aplicativos Fisicos: 2",
        "Diseno de Aplicativos Digitales: 4",
        "Manual de Identidad",
        "Atencion y asesoria al cliente",
        "Revisiones",
      ],
    },
    {
      nombre: "Logo e Identidad",
      descripcion: "Diseno de identidad de marca y logotipo",
      fase: 1,
      tipoPago: "unico",
      precioBase: 12093, // 699 USD
      tiempoEntrega: "7 - 15 dias",
      categoria: "diseno",
      nivel: "PYME",
      orden: 102,
      entregablesDefault: [
        "Investigacion de Tendencias, Mercado, Competencia y Demanda",
        "Creacion y Propuesta del Naming: 3",
        "Propuesta del Logotipo: 3",
        "Creacion Logotipo",
        "Aplicativos Fisicos: 4",
        "Aplicativos Digitales: 4",
        "Manual de Identidad",
        "Atencion y asesoria al cliente",
        "Revisiones",
        "Kit Basico para Redes Sociales (1 portada, 1 foto de perfil, 1 template RSS)",
      ],
    },
    {
      nombre: "Logo e Identidad",
      descripcion: "Diseno de identidad de marca y logotipo",
      fase: 1,
      tipoPago: "unico",
      precioBase: 17283, // 999 USD
      tiempoEntrega: "7 - 15 dias",
      categoria: "diseno",
      nivel: "Empresario",
      orden: 103,
      entregablesDefault: [
        "Investigacion de Tendencias, Mercado, Competencia y Demanda",
        "Creacion y Propuesta del Naming: 4",
        "Propuesta del Logotipo: 4",
        "Creacion Logotipo",
        "Aplicativos Fisicos: 6",
        "Aplicativos Digitales: 4",
        "Manual de Identidad",
        "Atencion y asesoria al cliente",
        "Revisiones",
        "Kit Basico para Redes Sociales (1 portada, 1 foto de perfil, 4 templates RSS)",
      ],
    },
    {
      nombre: "Logo e Identidad",
      descripcion: "Diseno de identidad de marca y logotipo",
      fase: 1,
      tipoPago: "unico",
      precioBase: 42368, // 2449 USD
      tiempoEntrega: "10 - 20 dias",
      categoria: "diseno",
      nivel: "Corporativo",
      orden: 104,
      entregablesDefault: [
        "Investigacion de Tendencias, Mercado, Competencia y Demanda",
        "Creacion y Propuesta del Naming: 5",
        "Propuesta del Logotipo: 5",
        "Creacion Logotipo",
        "Aplicativos Fisicos: 10",
        "Aplicativos Digitales: 4",
        "Manual de Identidad",
        "Atencion y asesoria al cliente",
        "Revisiones",
        "Kit Basico para Redes Sociales (3 portadas, 1 foto de perfil, 6 templates RSS)",
        "Iconografia",
        "Registro del IMPI (10 anos)",
      ],
    },

    // ── PAGINA WEB (Fase 1, unico) ──
    {
      nombre: "Pagina Web",
      descripcion: "Creacion, configuracion y optimizacion de sitio web",
      fase: 1,
      tipoPago: "unico",
      precioBase: 7768, // 449 USD
      tiempoEntrega: "15 - 30 dias",
      categoria: "sitio_web",
      nivel: "Emprendedor",
      orden: 111,
      entregablesDefault: [
        "Propuesta de Diseno: 2",
        "Creacion, Configuracion y Optimizacion de Sitio Web",
        "Configuracion de Chat en Sitio Web",
        "Optimizacion Basico SEO",
        "Optimizacion basica de Velocidad de Carga",
        "Estadisticas de Sitio Web (mensual)",
        "Cambios de Informacion al Mes (No Acumulable): 1",
        "Capacitacion basica para Manejo de Sitio Web",
        "Reuniones de Trabajo",
        "Alta en Buscadores",
        "Cuentas de E-mail con Dominio",
        "Paginas base (Gracias/Politicas/Terminos/Contacto/Nosotros/404)",
        "Diseno Responsivo",
        "Integracion de Formulario",
        "Espacio 12 GB",
        "Certificado Seguridad SSL (1 ano)",
        "Integracion de Hosting (1 ano)",
        "Asesoria y Adquisicion de Dominio (1 ano)",
      ],
    },
    {
      nombre: "Pagina Web",
      descripcion: "Creacion, configuracion y optimizacion de sitio web",
      fase: 1,
      tipoPago: "unico",
      precioBase: 13996, // 809 USD
      tiempoEntrega: "15 - 30 dias",
      categoria: "sitio_web",
      nivel: "PYME",
      orden: 112,
      entregablesDefault: [
        "Propuesta de Diseno: 4",
        "Creacion, Configuracion y Optimizacion de Sitio Web",
        "Configuracion de Chat en Sitio Web",
        "Optimizacion Basico SEO",
        "Optimizacion basica de Velocidad de Carga",
        "Estadisticas de Sitio Web (mensual)",
        "Cambios de Informacion al Mes (No Acumulable): 2",
        "Capacitacion basica para Manejo de Sitio Web",
        "Reuniones de Trabajo",
        "Alta en Buscadores",
        "Cuentas de E-mail con Dominio",
        "Paginas base (Gracias/Politicas/Terminos/Contacto/Nosotros/404)",
        "Diseno Responsivo",
        "Integracion de Formulario",
        "Espacio 12 GB",
        "Certificado Seguridad SSL (1 ano)",
        "Integracion de Hosting (1 ano)",
        "Asesoria y Adquisicion de Dominio (1 ano)",
      ],
    },
    {
      nombre: "Pagina Web",
      descripcion: "Creacion, configuracion y optimizacion de sitio web",
      fase: 1,
      tipoPago: "unico",
      precioBase: 21781, // 1259 USD
      tiempoEntrega: "20 - 35 dias",
      categoria: "sitio_web",
      nivel: "Empresario",
      orden: 113,
      entregablesDefault: [
        "Propuesta de Diseno: 6",
        "Creacion, Configuracion y Optimizacion de Sitio Web",
        "Configuracion de Chat en Sitio Web",
        "Optimizacion Basico SEO",
        "Optimizacion basica de Velocidad de Carga",
        "Estadisticas de Sitio Web (mensual)",
        "Cambios de Informacion al Mes (No Acumulable): 3",
        "Investigacion Tendencias, Mercado, Competencia y Demanda",
        "Capacitacion basica para Manejo de Sitio Web",
        "Reuniones de Trabajo",
        "Alta en Buscadores",
        "Cuentas de E-mail con Dominio",
        "Paginas base (Gracias/Politicas/Terminos/Contacto/Nosotros/404)",
        "Diseno Responsivo",
        "Integracion de Formulario",
        "Espacio 12 GB",
        "Integracion Base de Datos para Correo",
        "Certificado Seguridad SSL (1 ano)",
        "Integracion de Hosting (1 ano)",
        "Asesoria y Adquisicion de Dominio (1 ano)",
      ],
    },
    {
      nombre: "Pagina Web",
      descripcion: "Creacion, configuracion y optimizacion de sitio web",
      fase: 1,
      tipoPago: "unico",
      precioBase: 39254, // 2269 USD
      tiempoEntrega: "25 - 45 dias",
      categoria: "sitio_web",
      nivel: "Corporativo",
      orden: 114,
      entregablesDefault: [
        "Propuesta de Diseno: 8",
        "Creacion, Configuracion y Optimizacion de Sitio Web",
        "Configuracion de Chat en Sitio Web",
        "Optimizacion Avanzado SEO",
        "Optimizacion Avanzado de Velocidad de Carga",
        "Optimizacion SEO Local",
        "Estadisticas de Sitio Web (mensual)",
        "Cambios de Informacion al Mes (No Acumulable): 5",
        "Investigacion Tendencias, Mercado, Competencia y Demanda",
        "Escritura Comercial",
        "Capacitacion basica para Manejo de Sitio Web",
        "Reuniones de Trabajo",
        "Alta en Buscadores",
        "Cuentas de E-mail con Dominio",
        "Paginas base (incluye Bolsa de Trabajo)",
        "Diseno Responsivo",
        "Integracion de Formulario",
        "Espacio 12 GB",
        "Integracion Base de Datos para Correo",
        "Certificado Seguridad SSL (1 ano)",
        "Integracion de Hosting (1 ano)",
        "Asesoria y Adquisicion de Dominio (1 ano)",
        "Integracion CRM",
      ],
    },

    // ── TIENDA EN LINEA (Fase 1, unico) ── (hoja "Tienda en linea")
    {
      nombre: "Tienda en Linea",
      descripcion: "Desarrollo de tienda en linea (Magento, Shopify, WordPress)",
      fase: 1,
      tipoPago: "unico",
      precioBase: 17283, // 999 USD
      tiempoEntrega: "20 - 40 dias",
      categoria: "ecommerce",
      nivel: "Emprendedor",
      orden: 121,
      entregablesDefault: [
        "Configuracion en Tienda en Linea (Magento, Shopify, WordPress)",
        "Eleccion de plantilla y Estructura de diseno (UX, UI)",
        "Desarrollo y Estructura de tienda Optimizada para SEO",
        "Creacion y Configuracion de Categorias",
        "Diseno y Configuracion de Blog",
        "Carga de Productos: 100",
        "Capacitacion",
        "Atencion y asesoria al cliente",
        "Certificado Seguridad SSL (1 ano)",
        "Integracion de Hosting (1 ano)",
        "Asesoria y Adquisicion de Dominio (1 ano)",
        "Integracion de metodos de pago",
        "Integracion de metodos de envio",
        "Integracion de Chat",
        "Integracion y Configuracion de Google Analytics",
        "Integracion y Configuracion de Search Console",
      ],
    },
    {
      nombre: "Tienda en Linea",
      descripcion: "Desarrollo de tienda en linea (Magento, Shopify, WordPress)",
      fase: 1,
      tipoPago: "unico",
      precioBase: 26106, // 1509 USD
      tiempoEntrega: "25 - 45 dias",
      categoria: "ecommerce",
      nivel: "PYME",
      orden: 122,
      entregablesDefault: [
        "Configuracion en Tienda en Linea (Magento, Shopify, WordPress)",
        "Eleccion de plantilla y Estructura de diseno (UX, UI)",
        "Desarrollo y Estructura de tienda Optimizada para SEO",
        "Creacion y Configuracion de Categorias",
        "Diseno y Configuracion de Blog",
        "Carga de Productos: 250",
        "Configuracion de productos seleccionados y recomendados (upsell, cross selling)",
        "Capacitacion",
        "Atencion y asesoria al cliente",
        "Certificado Seguridad SSL (1 ano)",
        "Integracion de Hosting (1 ano)",
        "Asesoria y Adquisicion de Dominio (1 ano)",
        "Integracion de metodos de pago",
        "Integracion de metodos de envio",
        "Integracion de Chat",
        "Integracion y Configuracion de Google Analytics",
        "Integracion y Configuracion de Search Console",
        "Estrategias para recuperacion de carritos abandonados",
      ],
    },
    {
      nombre: "Tienda en Linea",
      descripcion: "Desarrollo de tienda en linea (Magento, Shopify, WordPress)",
      fase: 1,
      tipoPago: "unico",
      precioBase: 26106, // 1509 USD
      tiempoEntrega: "30 - 50 dias",
      categoria: "ecommerce",
      nivel: "Empresario",
      orden: 123,
      entregablesDefault: [
        "Configuracion en Tienda en Linea (Magento, Shopify, WordPress)",
        "Eleccion de plantilla y Estructura de diseno (UX, UI)",
        "Desarrollo y Estructura de tienda Optimizada para SEO",
        "Creacion y Configuracion de Categorias",
        "Diseno y Configuracion de Blog",
        "Carga de Productos: 500",
        "Configuracion de productos seleccionados y recomendados (upsell, cross selling)",
        "Desarrollo de Contenido SEO",
        "Asesoramiento para estrategias de promociones y descuentos",
        "Capacitacion",
        "Atencion y asesoria al cliente",
        "Certificado Seguridad SSL (1 ano)",
        "Integracion de Hosting (1 ano)",
        "Asesoria y Adquisicion de Dominio (1 ano)",
        "Integracion de metodos de pago",
        "Integracion de metodos de envio",
        "Integracion de Chat",
        "Integracion y Configuracion de Google Analytics",
        "Integracion y Configuracion de Search Console",
        "Estrategias para recuperacion de carritos abandonados",
      ],
    },

    // ── E-COMMERCE (Fase 1, unico) ── (hoja "Hemeroteca", version mas completa)
    {
      nombre: "E-commerce",
      descripcion: "Tienda en linea completa: plataforma, hosting, dominio y puesta en marcha",
      fase: 1,
      tipoPago: "unico",
      precioBase: 17283, // 999 USD
      tiempoEntrega: "20 - 40 dias",
      categoria: "ecommerce",
      variante: "Hemeroteca",
      nivel: "Emprendedor",
      orden: 131,
      entregablesDefault: [
        "Asesoria y Eleccion de Plataforma",
        "Hosting, Eleccion y Asesoria de Dominio",
        "Certificado SSL",
        "Asesoria y Eleccion de Plantilla Base",
        "Configuracion en Tienda en Linea",
        "Integracion Metodos de Pago",
        "Integracion Metodos de Envio",
        "Integracion de Chat: 1",
        "Configuracion Paginas Transaccionales",
        "Integracion Google Analytics",
        "Integracion Search Console",
        "Estructura Tienda en Linea Optimizada",
        "Creacion y Configuracion de Categorias",
        "Diseno y Configuracion de Blog",
        "Carga de Productos: 100",
        "Diseno y Personalizacion de Tienda",
        "Capacitacion y Puesta en Marcha",
        "Soporte por Correo Electronico (24 hrs)",
        "Juntas de Retroalimentacion cada Mes",
      ],
    },
    {
      nombre: "E-commerce",
      descripcion: "Tienda en linea completa: plataforma, hosting, dominio y puesta en marcha",
      fase: 1,
      tipoPago: "unico",
      precioBase: 26106, // 1509 USD
      tiempoEntrega: "25 - 45 dias",
      categoria: "ecommerce",
      variante: "Hemeroteca",
      nivel: "PYME",
      orden: 132,
      entregablesDefault: [
        "Asesoria y Eleccion de Plataforma",
        "Hosting, Eleccion y Asesoria de Dominio",
        "Certificado SSL",
        "Asesoria y Eleccion de Plantilla Base",
        "Configuracion en Tienda en Linea",
        "Integracion Metodos de Pago",
        "Integracion Metodos de Envio",
        "Integracion de Chat: 2",
        "Configuracion Paginas Transaccionales",
        "Integracion Google Analytics",
        "Integracion Search Console",
        "Estructura Tienda en Linea Optimizada",
        "Creacion y Configuracion de Categorias",
        "Diseno y Configuracion de Blog",
        "Carga de Productos: 250",
        "Diseno y Personalizacion de Tienda",
        "Capacitacion y Puesta en Marcha",
        "Soporte por Correo Electronico (12 hrs)",
        "Juntas de Retroalimentacion cada Mes",
      ],
    },
    {
      nombre: "E-commerce",
      descripcion: "Tienda en linea completa: plataforma, hosting, dominio y puesta en marcha",
      fase: 1,
      tipoPago: "unico",
      precioBase: 34756, // 2009 USD
      tiempoEntrega: "30 - 50 dias",
      categoria: "ecommerce",
      variante: "Hemeroteca",
      nivel: "Empresario",
      orden: 133,
      entregablesDefault: [
        "Asesoria y Eleccion de Plataforma",
        "Hosting, Eleccion y Asesoria de Dominio",
        "Certificado SSL",
        "Asesoria y Eleccion de Plantilla Base",
        "Configuracion en Tienda en Linea",
        "Integracion Metodos de Pago",
        "Integracion Metodos de Envio",
        "Integracion de Chat: 3",
        "Configuracion Paginas Transaccionales",
        "Integracion Google Analytics",
        "Integracion Search Console",
        "Estructura Tienda en Linea Optimizada",
        "Creacion y Configuracion de Categorias",
        "Diseno y Configuracion de Blog",
        "Carga de Productos: 500",
        "Diseno y Personalizacion de Tienda",
        "Capacitacion y Puesta en Marcha",
        "Soporte por Correo Electronico (8 hrs)",
        "Juntas de Retroalimentacion cada Mes",
        "Diseno Responsivo UX",
        "Configuracion de Carritos Abandonados",
        "Up-Selling, Cross-Selling",
      ],
    },
    {
      nombre: "E-commerce",
      descripcion: "Tienda en linea completa: plataforma, hosting, dominio y puesta en marcha",
      fase: 1,
      tipoPago: "unico",
      precioBase: 43579, // 2519 USD
      tiempoEntrega: "35 - 60 dias",
      categoria: "ecommerce",
      variante: "Hemeroteca",
      nivel: "Corporativo",
      orden: 134,
      entregablesDefault: [
        "Asesoria y Eleccion de Plataforma",
        "Hosting, Eleccion y Asesoria de Dominio",
        "Certificado SSL",
        "Asesoria y Eleccion de Plantilla Base",
        "Configuracion en Tienda en Linea",
        "Integracion Metodos de Pago",
        "Integracion Metodos de Envio",
        "Integracion de Chat: 4",
        "Configuracion Paginas Transaccionales",
        "Integracion Google Analytics",
        "Integracion Search Console",
        "Estructura Tienda en Linea Optimizada",
        "Creacion y Configuracion de Categorias",
        "Diseno y Configuracion de Blog",
        "Carga de Productos: ilimitados",
        "Diseno y Personalizacion de Tienda",
        "Capacitacion y Puesta en Marcha",
        "Soporte por Correo Electronico (inmediata)",
        "Juntas de Retroalimentacion cada Mes",
        "Diseno Responsivo UX",
        "Configuracion de Carritos Abandonados",
        "Up-Selling, Cross-Selling",
        "Desarrollo Contenido SEO",
        "Asesoramiento Promociones y Descuentos",
        "Configuracion Programas de Lealtad",
      ],
    },

    // ── MENU DIGITAL (Fase 1, unico) ──
    {
      nombre: "Menu Digital",
      descripcion: "Menu digital con QR personalizado",
      fase: 1,
      tipoPago: "unico",
      precioBase: 1713, // 99 USD
      tiempoEntrega: "7 - 15 dias",
      categoria: "sitio_web",
      nivel: "Emprendedor",
      orden: 141,
      entregablesDefault: [
        "Diseno de Menu Digital",
        "QR Personalizado / Dinamico",
        "Diseno de Pegatinas",
        "Un Idioma (Espanol)",
        "Lecturas Ilimitadas",
        "Alojamiento de Menu y QR",
        "Soporte por Ticket",
        "Juntas de Retroalimentacion Cada Mes",
      ],
    },
    {
      nombre: "Menu Digital",
      descripcion: "Menu digital con QR personalizado",
      fase: 1,
      tipoPago: "unico",
      precioBase: 3443, // 199 USD
      tiempoEntrega: "7 - 15 dias",
      categoria: "sitio_web",
      nivel: "PYME",
      orden: 142,
      entregablesDefault: [
        "Diseno de Menu Digital",
        "QR Personalizado / Dinamico",
        "Diseno de Pegatinas",
        "Un Idioma (Espanol)",
        "Lecturas Ilimitadas",
        "Alojamiento de Menu y QR",
        "Soporte por Ticket",
        "Juntas de Retroalimentacion Cada Mes",
        "Integracion de Redes Sociales",
        "Hasta 100 Productos",
        "Actualizaciones por Ano: 10",
        "Boton de WhatsApp",
        "Promocion Mensual",
        "Captacion de Base de Datos",
        "E-mail Marketing Automation",
        "Templates a Elegir: 5",
      ],
    },
    {
      nombre: "Menu Digital",
      descripcion: "Menu digital con QR personalizado",
      fase: 1,
      tipoPago: "unico",
      precioBase: 5173, // 299 USD
      tiempoEntrega: "10 - 20 dias",
      categoria: "sitio_web",
      nivel: "Empresario",
      orden: 143,
      entregablesDefault: [
        "Diseno de Menu Digital",
        "QR Personalizado / Dinamico",
        "Diseno de Pegatinas",
        "Un Idioma (Espanol)",
        "Lecturas Ilimitadas",
        "Alojamiento de Menu y QR",
        "Soporte por Ticket",
        "Juntas de Retroalimentacion Cada Mes",
        "Integracion de Redes Sociales",
        "Hasta 100 Productos",
        "Actualizaciones por Ano: 10",
        "Boton de WhatsApp",
        "Promocion Mensual",
        "Captacion de Base de Datos",
        "E-mail Marketing Automation",
        "Templates a Elegir: 5",
        "Pagina Web (Menu Digital)",
        "Pago en Linea",
        "Personalizacion de Productos",
        "Guia de Nutricion por Producto",
        "Multiples Addons",
        "Notificacion de Nueva Orden",
        "Mensajes de Horarios de Atencion",
        "Multiples Menus o Secciones",
        "100% Responsivo",
        "Etiquetas Personalizables",
      ],
    },

    // ── GOOGLE ADS (Fase 2, mensual) ──
    {
      nombre: "Google Ads",
      descripcion: "Creacion, configuracion y optimizacion de campanas Google Ads",
      fase: 2,
      tipoPago: "mensual",
      precioBase: 2578, // 149 USD
      tiempoEntrega: "Servicio mensual",
      categoria: "ads",
      nivel: "Emprendedor",
      orden: 201,
      entregablesDefault: [
        "Creacion y Configuracion de cuenta Google Ads",
        "Investigacion y Optimizacion de palabras clave positivas y negativas",
        "Creacion de Campanas Publicitarias: 1 a 3",
        "Optimizacion de presupuesto de Campanas diaria",
        "Integracion con Google Analytics",
        "Integracion de etiqueta de pixeles de conversion",
        "Reporte de Resultado mensual y junta de retroalimentacion",
        "Atencion y asesoria al cliente",
      ],
    },
    {
      nombre: "Google Ads",
      descripcion: "Creacion, configuracion y optimizacion de campanas Google Ads",
      fase: 2,
      tipoPago: "mensual",
      precioBase: 5173, // 299 USD
      tiempoEntrega: "Servicio mensual",
      categoria: "ads",
      nivel: "PYME",
      orden: 202,
      entregablesDefault: [
        "Creacion y Configuracion de cuenta Google Ads",
        "Investigacion y Optimizacion de palabras clave positivas y negativas",
        "Creacion de Campanas Publicitarias: 1 a 6",
        "Optimizacion de presupuesto de Campanas diaria",
        "Configuracion de Anuncios de Remarketing",
        "Integracion con Google Analytics",
        "Integracion de etiqueta de pixeles de conversion",
        "Reporte de Resultado mensual y junta de retroalimentacion",
        "Atencion y asesoria al cliente",
      ],
    },
    {
      nombre: "Google Ads",
      descripcion: "Creacion, configuracion y optimizacion de campanas Google Ads",
      fase: 2,
      tipoPago: "mensual",
      precioBase: 10363, // 599 USD
      tiempoEntrega: "Servicio mensual",
      categoria: "ads",
      nivel: "Empresario",
      orden: 203,
      entregablesDefault: [
        "Creacion y Configuracion de cuenta Google Ads",
        "Investigacion y Optimizacion de palabras clave positivas y negativas",
        "Creacion de Campanas Publicitarias: 10",
        "Optimizacion de presupuesto de Campanas diaria",
        "Configuracion de Anuncios de Remarketing",
        "Configuracion de Anuncios para Red Display",
        "Automatizacion de envio de Ficha de Prospectos",
        "Integracion con Google Analytics",
        "Integracion de etiqueta de pixeles de conversion",
        "Integracion de Herramientas de automatizacion",
        "Reporte de Resultado mensual y junta de retroalimentacion",
        "Atencion y asesoria al cliente",
      ],
    },
    {
      nombre: "Google Ads",
      descripcion: "Creacion, configuracion y optimizacion de campanas Google Ads",
      fase: 2,
      tipoPago: "mensual",
      precioBase: 17456, // 1009 USD
      tiempoEntrega: "Servicio mensual",
      categoria: "ads",
      nivel: "Corporativo",
      orden: 204,
      entregablesDefault: [
        "Creacion y Configuracion de cuenta Google Ads",
        "Investigacion y Optimizacion de palabras clave positivas y negativas",
        "Creacion de Campanas Publicitarias: 15",
        "Optimizacion de presupuesto de Campanas diaria",
        "Configuracion de Anuncios de Remarketing",
        "Configuracion de Anuncios para Red Display",
        "Configuracion de Google Merchant Center",
        "Configuracion y Optimizacion del Fit de productos",
        "Configuracion de Campanas para Shopping",
        "Configuracion de cuenta BING",
        "Configuracion de Campanas BING",
        "Automatizacion de envio de Ficha de Prospectos",
        "Integracion con Google Analytics",
        "Integracion de etiqueta de pixeles de conversion",
        "Integracion de Herramientas de automatizacion",
        "Reporte de Resultado mensual y junta de retroalimentacion",
        "Atencion y asesoria al cliente",
      ],
    },

    // ── FB & IG ADS (Fase 2, mensual) ──
    {
      nombre: "Facebook & Instagram Ads",
      descripcion: "Creacion y optimizacion de campanas en Meta (Facebook e Instagram)",
      fase: 2,
      tipoPago: "mensual",
      precioBase: 2578, // 149 USD
      tiempoEntrega: "Servicio mensual",
      categoria: "ads",
      nivel: "Emprendedor",
      orden: 211,
      entregablesDefault: [
        "Investigacion, Segmentacion y Optimizacion del Publico Objetivo",
        "Creacion y Configuracion del Administrador de Anuncios",
        "Creacion de Artes para Anuncios Publicitarios",
        "Creacion y Configuracion de Campanas Publicitarias: 1 a 3",
        "Configuracion de lista de Remarketing",
        "Optimizacion de presupuesto diario y campanas publicitarias",
        "Instalacion de Pixeles en Pag. Web",
        "Reporte de Resultado mensual y junta de retroalimentacion",
        "Atencion y asesoria al cliente",
      ],
    },
    {
      nombre: "Facebook & Instagram Ads",
      descripcion: "Creacion y optimizacion de campanas en Meta (Facebook e Instagram)",
      fase: 2,
      tipoPago: "mensual",
      precioBase: 5173, // 299 USD
      tiempoEntrega: "Servicio mensual",
      categoria: "ads",
      nivel: "PYME",
      orden: 212,
      entregablesDefault: [
        "Investigacion, Segmentacion y Optimizacion del Publico Objetivo",
        "Creacion y Configuracion del Administrador de Anuncios",
        "Creacion de Artes para Anuncios Publicitarios",
        "Creacion y Configuracion de Campanas Publicitarias: 1 a 6",
        "Configuracion de lista de Remarketing",
        "Optimizacion de presupuesto diario y campanas publicitarias",
        "Instalacion de Pixeles en Pag. Web",
        "Reporte de Resultado mensual y junta de retroalimentacion",
        "Atencion y asesoria al cliente",
      ],
    },
    {
      nombre: "Facebook & Instagram Ads",
      descripcion: "Creacion y optimizacion de campanas en Meta (Facebook e Instagram)",
      fase: 2,
      tipoPago: "mensual",
      precioBase: 6903, // 399 USD
      tiempoEntrega: "Servicio mensual",
      categoria: "ads",
      nivel: "Empresario",
      orden: 213,
      entregablesDefault: [
        "Investigacion, Segmentacion y Optimizacion del Publico Objetivo",
        "Creacion y Configuracion del Administrador de Anuncios",
        "Creacion de Artes para Anuncios Publicitarios",
        "Creacion y Configuracion de Campanas Publicitarias: 1 a 8",
        "Configuracion de lista de Remarketing",
        "Optimizacion de presupuesto diario y campanas publicitarias",
        "Instalacion de Pixeles en Pag. Web",
        "Integracion de herramientas de automatizacion",
        "Reporte de Resultado mensual y junta de retroalimentacion",
        "Atencion y asesoria al cliente",
      ],
    },
    {
      nombre: "Facebook & Instagram Ads",
      descripcion: "Creacion y optimizacion de campanas en Meta (Facebook e Instagram)",
      fase: 2,
      tipoPago: "mensual",
      precioBase: 13131, // 759 USD
      tiempoEntrega: "Servicio mensual",
      categoria: "ads",
      nivel: "Corporativo",
      orden: 214,
      entregablesDefault: [
        "Investigacion, Segmentacion y Optimizacion del Publico Objetivo",
        "Creacion y Configuracion del Administrador de Anuncios",
        "Creacion de Artes para Anuncios Publicitarios",
        "Creacion y Configuracion de Campanas Publicitarias: 1 a 15",
        "Creacion de Anuncios para Shopping",
        "Configuracion de lista de Remarketing",
        "Configuracion de catalogo de Productos de Facebook",
        "Optimizacion de presupuesto diario y campanas publicitarias",
        "Instalacion de Pixeles en Pag. Web",
        "Integracion de herramientas de automatizacion",
        "Reporte de Resultado mensual y junta de retroalimentacion",
        "Atencion y asesoria al cliente",
      ],
    },

    // ── MANEJO DE REDES SOCIALES (Fase 2, mensual) ──
    {
      nombre: "Manejo de Redes Sociales",
      descripcion: "Gestion y contenido de redes sociales",
      fase: 2,
      tipoPago: "mensual",
      precioBase: 6903, // 399 USD
      tiempoEntrega: "Servicio mensual",
      categoria: "redes",
      nivel: "Emprendedor",
      orden: 221,
      entregablesDefault: [
        "Creacion, Configuracion y/o Optimizacion de pagina de Facebook",
        "Medicion de conversiones",
        "Estrategia de contenido Publicitario",
        "Creacion de embudo de conversion",
        "Desarrollo de Cover",
        "Creacion de artes y copys para Post",
        "Posteos de Publicacion al mes: 10",
        "Asesoria al cliente por correo electronico (24 hrs)",
        "Informes periodicos",
        "Integracion de Google Analytics",
      ],
    },
    {
      nombre: "Manejo de Redes Sociales",
      descripcion: "Gestion y contenido de redes sociales",
      fase: 2,
      tipoPago: "mensual",
      precioBase: 12093, // 699 USD
      tiempoEntrega: "Servicio mensual",
      categoria: "redes",
      nivel: "PYME",
      orden: 222,
      entregablesDefault: [
        "Creacion, Configuracion y/o Optimizacion de pagina de Facebook",
        "Medicion de conversiones",
        "Estrategia de contenido Publicitario",
        "Creacion de embudo de conversion",
        "Desarrollo de Cover",
        "Creacion de artes y copys para Post",
        "Posteos de Publicacion al mes: 15",
        "Asesoria al cliente por correo electronico (24 hrs)",
        "Informes periodicos",
        "Integracion de Google Analytics",
        "Integracion Search Console",
        "Desarrollo Tienda en Linea Optimizada",
        "Video",
      ],
    },
    {
      nombre: "Manejo de Redes Sociales",
      descripcion: "Gestion y contenido de redes sociales",
      fase: 2,
      tipoPago: "mensual",
      precioBase: 17456, // 1009 USD
      tiempoEntrega: "Servicio mensual",
      categoria: "redes",
      nivel: "Empresario",
      orden: 223,
      entregablesDefault: [
        "Creacion, Configuracion y/o Optimizacion de pagina de Facebook",
        "Medicion de conversiones",
        "Estrategia de contenido Publicitario",
        "Creacion de embudo de conversion",
        "Desarrollo de Cover",
        "Creacion de artes y copys para Post",
        "Posteos de Publicacion al mes: 15",
        "Asesoria al cliente por correo electronico (24 hrs)",
        "Informes periodicos",
        "Integracion de Google Analytics",
        "Integracion Search Console",
        "Desarrollo Tienda en Linea Optimizada",
        "Video",
        "Gifs",
        "Dinamicas",
      ],
    },
    {
      nombre: "Manejo de Redes Sociales",
      descripcion: "Gestion y contenido de redes sociales",
      fase: 2,
      tipoPago: "mensual",
      precioBase: 42195, // 2439 USD
      tiempoEntrega: "Servicio mensual",
      categoria: "redes",
      nivel: "Corporativo",
      orden: 224,
      entregablesDefault: [
        "Creacion, Configuracion y/o Optimizacion de pagina de Facebook",
        "Medicion de conversiones",
        "Estrategia de contenido Publicitario",
        "Creacion de embudo de conversion",
        "Desarrollo de Cover",
        "Creacion de artes y copys para Post",
        "Posteos de Publicacion al mes: 15",
        "Asesoria al cliente por correo electronico (24 hrs)",
        "Informes periodicos",
        "Integracion de Google Analytics",
        "Integracion Search Console",
        "Desarrollo Tienda en Linea Optimizada",
        "Video",
        "Gifs",
        "Dinamicas",
        "Concursos",
        "Manejo Inmediato de Crisis",
      ],
    },

    // ── SEO (Fase 3, mensual) ──
    // NOTA: el Excel origen traia Empresario y Corporativo a 199 USD (error de copia:
    // mismo precio que Emprendedor pese a tener mas features). Corregido al patron
    // lineal +$100/nivel (5/10/15/20 keywords -> 199/299/399/499 USD).
    {
      nombre: "Posicionamiento SEO",
      descripcion: "Estrategia y posicionamiento SEO mensual",
      fase: 3,
      tipoPago: "mensual",
      precioBase: 3443, // 199 USD
      tiempoEntrega: "Servicio mensual",
      categoria: "seo",
      nivel: "Emprendedor",
      orden: 301,
      entregablesDefault: [
        "No. KeyWords: 5",
        "Estudio y definicion de Palabras Clave",
        "Analisis de la competencia",
        "Optimizacion tecnica de la estructura del Sitio a nivel SEO",
        "Optimizacion de la velocidad de carga en Sitio",
        "Creacion y Optimizacion del Sitemap.xml",
        "Reporte mensual de trafico y posicion Web",
        "Integracion y Configuracion de Google Search Console",
        "Integracion y Configuracion de Google Analytics",
        "Plan para desarrollo de contenido Estrategico para SEO",
        "Estrategia y Generacion de BackLinks",
        "Alta de Buscadores",
        "Generacion de trafico social a tu Sitio Web",
        "Sindicacion en Redes Sociales Externas",
        "Atencion y asesoria al cliente",
      ],
    },
    {
      nombre: "Posicionamiento SEO",
      descripcion: "Estrategia y posicionamiento SEO mensual",
      fase: 3,
      tipoPago: "mensual",
      precioBase: 5173, // 299 USD
      tiempoEntrega: "Servicio mensual",
      categoria: "seo",
      nivel: "PYME",
      orden: 302,
      entregablesDefault: [
        "No. KeyWords: 10",
        "Estudio y definicion de Palabras Clave",
        "Analisis de la competencia",
        "Optimizacion tecnica de la estructura del Sitio a nivel SEO",
        "Optimizacion de la velocidad de carga en Sitio",
        "Optimizacion de SEO local (Google My Business)",
        "Creacion y Optimizacion del Sitemap.xml",
        "Reporte mensual de trafico y posicion Web",
        "Integracion y Configuracion de Google Search Console",
        "Integracion y Configuracion de Google Analytics",
        "Plan para desarrollo de contenido Estrategico para SEO",
        "Estrategia y Generacion de BackLinks",
        "Alta de Buscadores",
        "Generacion de trafico social a tu Sitio Web",
        "Sindicacion en Redes Sociales Externas",
        "Atencion y asesoria al cliente",
      ],
    },
    {
      nombre: "Posicionamiento SEO",
      descripcion: "Estrategia y posicionamiento SEO mensual",
      fase: 3,
      tipoPago: "mensual",
      precioBase: 6903, // 399 USD (corregido)
      tiempoEntrega: "Servicio mensual",
      categoria: "seo",
      nivel: "Empresario",
      orden: 303,
      entregablesDefault: [
        "No. KeyWords: 15",
        "Estudio y definicion de Palabras Clave",
        "Analisis de la competencia",
        "Optimizacion tecnica de la estructura del Sitio a nivel SEO",
        "Optimizacion de la velocidad de carga en Sitio",
        "Optimizacion de SEO local (Google My Business)",
        "Creacion y Optimizacion del Sitemap.xml",
        "Reporte mensual de trafico y posicion Web",
        "Integracion y Configuracion de Google Search Console: 15",
        "Integracion y Configuracion de Google Analytics",
        "Plan para desarrollo de contenido Estrategico para SEO",
        "Estrategia y Generacion de BackLinks",
        "Alta de Buscadores",
        "Generacion de trafico social a tu Sitio Web",
        "Sindicacion en Redes Sociales Externas",
        "Desarrollo de contenido para Sitios Externos",
        "Atencion y asesoria al cliente",
      ],
    },
    {
      nombre: "Posicionamiento SEO",
      descripcion: "Estrategia y posicionamiento SEO mensual",
      fase: 3,
      tipoPago: "mensual",
      precioBase: 8633, // 499 USD (corregido)
      tiempoEntrega: "Servicio mensual",
      categoria: "seo",
      nivel: "Corporativo",
      orden: 304,
      entregablesDefault: [
        "No. KeyWords: 20",
        "Estudio y definicion de Palabras Clave",
        "Analisis de la competencia",
        "Optimizacion tecnica de la estructura del Sitio a nivel SEO",
        "Optimizacion de la velocidad de carga en Sitio",
        "Optimizacion de SEO local (Google My Business)",
        "Creacion y Optimizacion del Sitemap.xml",
        "Reporte mensual de trafico y posicion Web",
        "Integracion y Configuracion de Google Search Console: 15",
        "Integracion y Configuracion de Google Analytics",
        "Plan para desarrollo de contenido Estrategico para SEO",
        "Estrategia y Generacion de BackLinks",
        "Alta de Buscadores",
        "Generacion de trafico social a tu Sitio Web",
        "Sindicacion en Redes Sociales Externas",
        "Desarrollo de contenido para Sitios Externos",
        "Atencion y asesoria al cliente",
      ],
    },

    // ── ESTRATEGIA EMPRESARIAL EN ECOMMERCE (Fase 0, unico, sin niveles ni precio en Excel) ──
    {
      nombre: "Estrategia Empresarial en Ecommerce",
      descripcion: "Auditoria y estrategia integral para ecommerce (SEO, tecnica y seguridad Shopify, estudios de mercado/competencia y embudos de venta)",
      fase: 0,
      tipoPago: "unico",
      precioBase: 12900,
      tiempoEntrega: "10 - 20 dias",
      categoria: "estrategia",
      orden: 100,
      entregablesDefault: [
        "Auditoria completa de situacion actual del SEO del Sitio",
        "Auditoria Tecnica de Shopify",
        "Auditoria en Seguridad de Shopify",
        "Estudio de canales de comunicacion y captacion",
        "Estudio de Segmentos de Mercado para Landing Pages de prospeccion",
        "Estudio de Keyword Research para Categorizacion Jerarquica de Ecommerce",
        "Estudio de Keyword Research para creacion de Landing Page para prospeccion",
        "Estudio de competencia organica",
        "Estudio de competencia pagada",
        "Estudio de tendencias",
        "Adicional: Embudo de ventas para Ecommerce",
        "Adicional: Embudo de ventas para captacion",
      ],
    },
  ];

  for (const servicio of servicios) {
    const catNombre = catAlias[servicio.categoria] || "Desarrollo Personalizado";
    const servicioId =
      servicio.nombre.toLowerCase().replace(/\s+/g, "-").substring(0, 30) + "-" + servicio.orden;
    await prisma.servicioCatalogo.upsert({
      where: { id: servicioId },
      update: {},
      create: {
        id: servicioId,
        nombre: servicio.nombre,
        descripcion: servicio.descripcion,
        fase: servicio.fase,
        tipoPago: servicio.tipoPago,
        precioBase: servicio.precioBase,
        tiempoEntrega: servicio.tiempoEntrega,
        entregablesDefault: servicio.entregablesDefault,
        categoriaId: catMap[catNombre] || null,
        variante: ("variante" in servicio ? servicio.variante : null) || null,
        nivel: ("nivel" in servicio ? servicio.nivel : null) || null,
        orden: servicio.orden,
      },
    });
  }

  const allServicios = await prisma.servicioCatalogo.findMany();

  // ── PAQUETE GENERAL ──
  const paquete = await prisma.paquete.upsert({
    where: { id: "paquete-general" },
    update: {},
    create: {
      id: "paquete-general",
      nombre: "General",
      descripcion: "Paquete completo de servicios de marketing digital",
      activo: true,
    },
  });

  const fasesGeneral = [
    { nombre: "Auditoria / Acompanamiento", orden: 0 },
    { nombre: "Setup e Infraestructura", orden: 1 },
    { nombre: "Publicidad y Manejo", orden: 2 },
    { nombre: "Contenido y SEO", orden: 3 },
  ];

  const faseMap: Record<number, string> = {};
  for (const fg of fasesGeneral) {
    const faseId = `fase-general-${fg.orden}`;
    const created = await prisma.fasePaquete.upsert({
      where: { id: faseId },
      update: { nombre: fg.nombre, orden: fg.orden },
      create: {
        id: faseId,
        paqueteId: paquete.id,
        nombre: fg.nombre,
        orden: fg.orden,
      },
    });
    faseMap[fg.orden] = created.id;
  }

  for (const s of allServicios) {
    const fasePaqueteId = faseMap[s.fase];
    if (fasePaqueteId) {
      await prisma.servicioPaquete.upsert({
        where: {
          servicioCatalogoId_fasePaqueteId: {
            servicioCatalogoId: s.id,
            fasePaqueteId,
          },
        },
        update: {},
        create: {
          servicioCatalogoId: s.id,
          fasePaqueteId,
        },
      });
    }
  }

  // ── PAQUETES RECOMENDADOS PYME ──
  // Resuelve un servicio del catalogo por nombre (+ nivel opcional). El nivel
  // desambigua servicios con nombre repetido (ej. "Posicionamiento SEO" existe
  // generico con nivel null y tambien por nivel). Lanza error si no resuelve
  // exactamente 1 servicio para que cualquier nombre mal escrito reviente aqui.
  const findServId = (nombre: string, nivel: string | null = null): string => {
    const matches = allServicios.filter(
      (s) => s.nombre === nombre && (s.nivel ?? null) === (nivel ?? null)
    );
    if (matches.length !== 1) {
      throw new Error(
        `Paquete PyME: '${nombre}' (nivel=${nivel}) resolvio ${matches.length} servicios`
      );
    }
    return matches[0].id;
  };

  type ServRef = { nombre: string; nivel?: string | null };
  type PaqueteDef = {
    id: string;
    nombre: string;
    descripcion: string;
    fases: { orden: number; nombre: string; servicios: ServRef[] }[];
  };

  const FASE_NOMBRES = [
    "Auditoria / Acompanamiento",
    "Setup e Infraestructura",
    "Publicidad y Manejo",
    "Contenido y SEO",
  ];

  const paquetesPyme: PaqueteDef[] = [
    {
      id: "paquete-arranque",
      nombre: "Arranque Esencial",
      descripcion:
        "Inicio - cualquier giro. Minimo viable para una PyME que arranca: presencia profesional en redes y Google, y primeros clientes.",
      fases: [
        { orden: 0, nombre: FASE_NOMBRES[0], servicios: [{ nombre: "Auditoria en Redes Sociales" }] },
        {
          orden: 1,
          nombre: FASE_NOMBRES[1],
          servicios: [
            { nombre: "Creacion y Optimizacion de Redes Sociales" },
            { nombre: "Creacion y Optimizacion de la Ficha de Google My Business" },
          ],
        },
        { orden: 2, nombre: FASE_NOMBRES[2], servicios: [{ nombre: "Manejo Basico de Redes Sociales" }] },
      ],
    },
    {
      id: "paquete-marca",
      nombre: "Marca + Presencia",
      descripcion:
        "Inicio - marca nueva o personal. Imagen profesional (identidad), redes y primeras campanas de alcance antes de invertir en pauta fuerte.",
      fases: [
        { orden: 0, nombre: FASE_NOMBRES[0], servicios: [{ nombre: "Auditoria en Redes Sociales" }] },
        {
          orden: 1,
          nombre: FASE_NOMBRES[1],
          servicios: [
            { nombre: "Logo e Identidad", nivel: "Emprendedor" },
            { nombre: "Creacion y Optimizacion de Redes Sociales" },
            { nombre: "Creacion y Optimizacion de la Ficha de Google My Business" },
          ],
        },
        {
          orden: 2,
          nombre: FASE_NOMBRES[2],
          servicios: [
            { nombre: "Manejo Basico de Redes Sociales" },
            { nombre: "Manejo y Optimizacion de Meta Ads" },
          ],
        },
        { orden: 3, nombre: FASE_NOMBRES[3], servicios: [{ nombre: "Desarrollo de Plan de Contenido" }] },
      ],
    },
    {
      id: "paquete-local",
      nombre: "Negocio Local en Crecimiento",
      descripcion:
        "Crecimiento - giro local (restaurante, consultorio, tienda fisica, servicios). Visibilidad local y captacion por WhatsApp/llamada: web, ficha de Google, redes, Meta Ads y SEO local.",
      fases: [
        { orden: 0, nombre: FASE_NOMBRES[0], servicios: [{ nombre: "Auditoria en Sitio Web" }] },
        {
          orden: 1,
          nombre: FASE_NOMBRES[1],
          servicios: [
            { nombre: "Pagina Web", nivel: "Emprendedor" },
            { nombre: "Creacion y Optimizacion de la Ficha de Google My Business" },
            { nombre: "Creacion y Optimizacion de Redes Sociales" },
          ],
        },
        {
          orden: 2,
          nombre: FASE_NOMBRES[2],
          servicios: [
            { nombre: "Manejo Basico de Redes Sociales" },
            { nombre: "Manejo y Optimizacion de Meta Ads" },
          ],
        },
        { orden: 3, nombre: FASE_NOMBRES[3], servicios: [{ nombre: "Posicionamiento SEO" }] },
      ],
    },
    {
      id: "paquete-leads-b2b",
      nombre: "Servicios / B2B: Generacion de Leads",
      descripcion:
        "Crecimiento - servicios profesionales / B2B. Motor de prospeccion: sitio web solido, CRM Bucefalo, campanas de Google Ads, contenido y SEO.",
      fases: [
        {
          orden: 0,
          nombre: FASE_NOMBRES[0],
          servicios: [{ nombre: "Auditoria en Sitio Web" }, { nombre: "Estudio Digital de Mercado" }],
        },
        {
          orden: 1,
          nombre: FASE_NOMBRES[1],
          servicios: [
            { nombre: "Diseno de Sitio Web (WordPress)" },
            { nombre: "Configuracion y Puesta en Marcha del CRM Bucefalo" },
            { nombre: "Configuracion, Optimizacion y Puesta en Marcha de Google Ads y Meta Ads" },
          ],
        },
        {
          orden: 2,
          nombre: FASE_NOMBRES[2],
          servicios: [
            { nombre: "Configuracion y Optimizacion Google Ads" },
            { nombre: "Plan Mensual CRM Bucefalo" },
          ],
        },
        {
          orden: 3,
          nombre: FASE_NOMBRES[3],
          servicios: [{ nombre: "Desarrollo de Plan de Contenido" }, { nombre: "Posicionamiento SEO" }],
        },
      ],
    },
    {
      id: "paquete-ecommerce",
      nombre: "Ecommerce Lanzamiento",
      descripcion:
        "Inicio / Crecimiento - ecommerce. Vender en linea desde cero con buen setup de medicion y pauta: tienda WooCommerce, CRM y campanas de Google y Meta.",
      fases: [
        { orden: 0, nombre: FASE_NOMBRES[0], servicios: [{ nombre: "Auditoria en Ecommerce" }] },
        {
          orden: 1,
          nombre: FASE_NOMBRES[1],
          servicios: [
            { nombre: "Diseno de Ecommerce (WooCommerce)" },
            { nombre: "Configuracion, Optimizacion y Puesta en Marcha de Google Ads y Meta Ads" },
            { nombre: "Configuracion y Puesta en Marcha del CRM Bucefalo" },
          ],
        },
        {
          orden: 2,
          nombre: FASE_NOMBRES[2],
          servicios: [
            { nombre: "Manejo y Optimizacion de Meta Ads" },
            { nombre: "Configuracion y Optimizacion Google Ads" },
          ],
        },
      ],
    },
    {
      id: "paquete-360",
      nombre: "Escalamiento 360 Integral",
      descripcion:
        "Escalamiento - negocio consolidado, cualquier giro. Paquete tope: ads en niveles altos, redes profesionales, contenido, SEO completo y acompanamiento estrategico. El asesor recorta segun presupuesto.",
      fases: [
        {
          orden: 0,
          nombre: FASE_NOMBRES[0],
          servicios: [
            { nombre: "Auditoria en Sitio Web" },
            { nombre: "Auditoria de cuentas Google Ads y Meta Ads" },
            { nombre: "Estudio Digital de Mercado" },
            { nombre: "Plan de Acompanamiento Integral" },
          ],
        },
        {
          orden: 1,
          nombre: FASE_NOMBRES[1],
          servicios: [
            { nombre: "Diseno de Identidad Corporativa" },
            { nombre: "Diseno de Sitio Web (WordPress)" },
            { nombre: "Configuracion y Puesta en Marcha del CRM Bucefalo" },
            { nombre: "Configuracion, Optimizacion y Puesta en Marcha de Google Ads y Meta Ads" },
          ],
        },
        {
          orden: 2,
          nombre: FASE_NOMBRES[2],
          servicios: [
            { nombre: "Google Ads", nivel: "Empresario" },
            { nombre: "Facebook & Instagram Ads", nivel: "Empresario" },
            { nombre: "Manejo de Redes Sociales", nivel: "PYME" },
            { nombre: "Plan Mensual CRM Bucefalo" },
          ],
        },
        {
          orden: 3,
          nombre: FASE_NOMBRES[3],
          servicios: [
            { nombre: "Desarrollo de Plan de Contenido" },
            { nombre: "Generacion de Contenido" },
            { nombre: "Estrategia SEO Completa" },
          ],
        },
      ],
    },
  ];

  for (const pq of paquetesPyme) {
    const paqueteRec = await prisma.paquete.upsert({
      where: { id: pq.id },
      update: { nombre: pq.nombre, descripcion: pq.descripcion, activo: true },
      create: { id: pq.id, nombre: pq.nombre, descripcion: pq.descripcion, activo: true },
    });

    for (const fase of pq.fases) {
      const faseId = `fase-${pq.id}-${fase.orden}`;
      const faseCreated = await prisma.fasePaquete.upsert({
        where: { id: faseId },
        update: { nombre: fase.nombre, orden: fase.orden },
        create: { id: faseId, paqueteId: paqueteRec.id, nombre: fase.nombre, orden: fase.orden },
      });

      for (const ref of fase.servicios) {
        const servicioCatalogoId = findServId(ref.nombre, ref.nivel ?? null);
        await prisma.servicioPaquete.upsert({
          where: {
            servicioCatalogoId_fasePaqueteId: {
              servicioCatalogoId,
              fasePaqueteId: faseCreated.id,
            },
          },
          update: {},
          create: { servicioCatalogoId, fasePaqueteId: faseCreated.id },
        });
      }
    }
  }

  const bonos = [
    { numero: 1, titulo: "Servicio Centinela Web", descripcion: "30 minutos mensuales en servicios Centinela (Sitio Web)" },
    { numero: 2, titulo: "Workshop Buyer Persona", descripcion: "Workshop Estrategico de Buyer Persona" },
    { numero: 3, titulo: "Workshop Propuesta de Valor", descripcion: "Workshop de Propuestas de Valor y Oferta Irresistible" },
    { numero: 4, titulo: "Membresia Premium", descripcion: "1 ano de Membresia Premium" },
    { numero: 5, titulo: "Mes Gratis Bucefalo", descripcion: "Un mes gratis de Bucefalo CRM, Marketing y Ventas" },
    { numero: 6, titulo: "Script de Ventas", descripcion: "Script de Ventas con mas de 100 complementos" },
  ];

  if ((await prisma.bono.count()) === 0) {
    for (const bono of bonos) {
      await prisma.bono.create({ data: bono });
    }
  }

  const planes = [
    { meses: 3, tasa: 0.077, comision: 2.5, montoMinimo: 300, iva: 0.16 },
    { meses: 6, tasa: 0.107, comision: 2.5, montoMinimo: 600, iva: 0.16 },
    { meses: 9, tasa: 0.137, comision: 2.5, montoMinimo: 900, iva: 0.16 },
    { meses: 12, tasa: 0.167, comision: 2.5, montoMinimo: 1200, iva: 0.16 },
  ];

  for (const plan of planes) {
    await prisma.financiamientoPlan.upsert({
      where: { meses: plan.meses },
      update: {},
      create: plan,
    });
  }

  const configs = [
    {
      clave: "razon_social",
      valor: "URIEL JARETH ALVARADO ORTIZ",
    },
    {
      clave: "rfc",
      valor: "AAOU970201SU7",
    },
    {
      clave: "domicilio_fiscal",
      valor: "EMILIANO ZAPATA S/N, CUAMIO, CUITZEO, MICHOACAN DE OCAMPO CP 58855",
    },
    {
      clave: "cuenta_nacional",
      valor: "012227015788120440",
    },
    {
      clave: "clabe_interbancaria",
      valor: "012227015788120440",
    },
    {
      clave: "cuenta_internacional",
      valor: "Beneficiario: URIEL JARETH ALVARADO ORTIZ\nCLABE: 012227015788120440\nBanco: BBVA",
    },
    {
      clave: "cuenta_internacional_swift",
      valor: "Beneficiario: URIEL JARETH ALVARADO ORTIZ\nCodigo SWIFT / BIC: BCMRMXMMPYM\nCLABE: 012227015788120440\nBanco: BBVA Mexico",
    },
    {
      clave: "hora_centinela",
      valor: "700",
    },
    {
      clave: "anualidad_hosting",
      valor: "5000",
    },
    {
      clave: "iva",
      valor: "0.16",
    },
    {
      clave: "terminos_condiciones",
      valor: "- Esta cotizacion tiene una vigencia de 15 dias habiles.\n- Cualquier ajuste al proyecto despues de la aprobacion del contenido afectara la fecha de entrega y por consiguiente el costo.\n- El cliente debera proporcionar la informacion solicitada por Uriel Jareth Consulting en tiempo y forma.\n- Si la falta de informacion provoca un excedente en los plazos de entrega del proyecto, las horas adicionales de servicio se cotizaran por separado.\n- Los pagos correspondientes a los servicios mensuales deberan realizarse en los primeros 5 dias del mes.\n- Todo el material e informacion necesarios para la realizacion del sitio web deberan ser entregados en un plazo maximo de 40 dias naturales a partir del arranque del proyecto.",
    },
    {
      clave: "no_incluye",
      valor: "- Generacion de disenos, videos, traducciones, cambios de divisas y unidades, o cualquier servicio externo a lo cotizado. (Estos servicios son Extras, pueden ser realizados por Uriel Jareth Consulting y se cotizan como adicionales mediante cotizacion).\n- Redaccion de entradas de Blog.\n- Integracion de Servicios de terceros ajenos a los cotizados.\n- Servicio de Recuperacion de Accesos de: Google Analytics, Google Tag Manager, Google Search Console, Google Ads, y Meta Ads (En Caso de Requerir el Servicio se Aplicara uso de Hora Centinela).\n- Creacion de Redes Sociales (En Caso de Requerir el Servicio Incluira un Costo Adicional).",
    },
    {
      clave: "notas_adicionales",
      valor: "- El presente proyecto debera tener un responsable oficial, a quien se le compartiran los avances y con quien se mantendra la comunicacion.\n- La Hora Centinela tiene un precio de $700.00 MXN.\n- Los servicios incluyen la entrega de archivos finales listos para su uso (JPG, PNG, PDF, etc.). Los archivos editables/fuente (AI, PSD) son propiedad intelectual de Uriel Jareth Consulting y no estan incluidos, salvo en proyectos de Branding/Logotipos.\n- SI EL PROYECTO SE PAUSA POR RAZONES AJENAS A URIEL JARETH CONSULTING O FALTA DE CONTINUIDAD, ESTO GENERARA COSTO EXTRA PARA RETOMAR EL PROYECTO (SE CONSIDERARA UN COSTO QUE PUEDE IR DEL 15% AL 30% CON BASE A LA COTIZACION INICIAL).",
    },
    {
      clave: "color_primario",
      valor: "#2563eb",
    },
    {
      clave: "color_secundario",
      valor: "#1e293b",
    },
    {
      clave: "logo_base64",
      valor: "",
    },
  ];

  for (const config of configs) {
    await prisma.configuracion.upsert({
      where: { clave: config.clave },
      update: { valor: config.valor },
      create: config,
    });
  }

  console.log("Seed completed successfully!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
